name: Kernel Builder

on:
  workflow_call:
    inputs:
      KSU:
        type: string
        required: true
      SUSFS:
        type: boolean
        required: true
      LXC:
        type: boolean
        required: true
      BBG:
        type: boolean
        required: true

    outputs:
      kernel_version:
        description: "Kernel version"
        value: ${{ jobs.build.outputs.kernel_version }}
      susfs_version:
        description: "SUSFS version"
        value: ${{ jobs.build.outputs.susfs_version }}
      toolchain:
        description: "Toolchain"
        value: ${{ jobs.build.outputs.toolchain }}
      build_date:
        description: "Build timestamp"
        value: ${{ jobs.build.outputs.build_date }}
      release_repo:
        description: "Release repo"
        value: ${{ jobs.build.outputs.release_repo }}
      release_branch:
        description: "Release branch"
        value: ${{ jobs.build.outputs.release_branch }}
      kernel_name:
        description: "Kernel name"
        value: ${{ jobs.build.outputs.kernel_name }}

  workflow_dispatch:
    inputs:
      KSU:
        description: "KernelSU variant"
        default: "NONE"
        type: choice
        options: ["NONE", "OFFICIAL", "NEXT", "SUKI"]

      SUSFS:
        description: "Include SUSFS?"
        default: false
        type: boolean

      LXC:
        description: "Apply LXC patch?"
        default: false
        type: boolean
      
      BBG:
        description: "Include Baseband-guard?"
        default: false
        type: boolean

env:
  DEBIAN_FRONTEND: noninteractive
  MAN_DISABLE: true
  FORCE_COLOR: "1"
  TTY_COMPATIBLE: "1"
  TERM: xterm-256color

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      kernel_version: ${{ steps.build.outputs.kernel_version }}
      susfs_version: ${{ steps.build.outputs.susfs_version }}
      toolchain: ${{ steps.build.outputs.toolchain }}
      build_date: ${{ steps.build.outputs.build_date }}
      release_repo: ${{ steps.build.outputs.release_repo }}
      release_branch: ${{ steps.build.outputs.release_branch }}
      kernel_name: ${{ steps.build.outputs.kernel_name }}

    steps:
      - name: Fail SUSFS requirement check
        if: ${{ inputs.SUSFS == true && inputs.KSU == 'NONE' }}
        run: |
          echo "::error::Cannot use SUSFS without KernelSU"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq \
            bc bison curl flex git tar wget aria2 jq zip zstd upx build-essential dwarves libdw-dev libdwarf-dev libelf-dev zlib1g-dev libbpf-dev libssl-dev libncurses-dev libcap-dev libz-dev pkg-config
          sudo apt-get clean && sudo apt-get autoclean
          sudo apt-get autoremove -y

      - name: Cache Clang
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang/
          key: ${{ runner.os }}-custom-tools-v1

      - name: Install Clang via Git
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          mkdir -p /home/runner/work/xaga_esk_builder/xaga_esk_builder/
          git clone --branch llvm-r536225-release --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang
          rm -rf /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang/clang-3289846
          rm -rf /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang/clang-r522817
          rm -rf /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang/clang-r530567
          rm -rf /home/runner/work/xaga_esk_builder/xaga_esk_builder/clang/.git

      - name: Build
        id: build
        env:
          KSU: ${{ inputs.KSU }}
          SUSFS: ${{ inputs.SUSFS }}
          LXC: ${{ inputs.LXC }}
          BBG: ${{ inputs.BBG }}
          SOURCE_DATE_EPOCH: "1704067200"
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload kernel image artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-Image
          path: /home/runner/work/xaga_esk_builder/xaga_esk_builder/kernel/out/arch/arm64/boot/Image
